
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erik
 */
public class directorio2 extends javax.swing.JFrame {
/**
 * instanciar objeto
 */
    int x, y;
    private DefaultTableModel modelo;
    /**
     * Creates new form directorio2
     */
    public directorio2() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Primer apellido");
        modelo.addColumn("Segundo apelliudo");
        modelo.addColumn("Fecha de nacimiento");
        modelo.addColumn("Edad");
        modelo.addColumn("Codigo");
        this.Tabla.setModel(modelo);
        hideComp();
    }
    
    /**
     * METODO
     **/
    
    private void delTable(){
        int filas = Tabla.getRowCount();
        for( int i=0;i<filas;i++){
            modelo.removeRow(i);
        }
    }
    
    protected void setFilas(String datos[]){
        modelo.addRow(datos);
    }
    
    private void hideComp(){
        tfX.setVisible(false);
        tfY.setVisible(false);
    }
    
    protected void cargarArchivos() throws IOException{
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int resultado = fc.showSaveDialog(this);
        if(resultado== JFileChooser.CANCEL_OPTION){
        return;
    }
        File archivo = fc.getSelectedFile();
        
        try{
            FileReader fr = new FileReader(archivo);
            BufferedReader bf = new BufferedReader(fr);
            String linea;
            linea=bf.readLine();
            String [] lista = new String[modelo.getColumnCount()];
            while(linea!=null){
                StringTokenizer st = new StringTokenizer(linea,",");
                lista[0]=st.nextToken();
                lista[1]=st.nextToken();
                lista[2]=st.nextToken();
                lista[3]=st.nextToken();
                lista[4]=st.nextToken();
                lista[5]=st.nextToken();
                
                modelo.addRow(lista);
                linea = bf.readLine();
            }
            bf.close();
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,"error al encontrar el archivo en la carpeta del proyecto","Advertencia", JOptionPane.ERROR_MESSAGE);
        }//fin de try
    }//fin de cargarArchivo
    
    protected void guardarArchivo(){
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int resultado = fc.showSaveDialog(this);
        if(resultado== JFileChooser.CANCEL_OPTION){
        return;
    }
        File archivo = fc.getSelectedFile();
        try{
            FileWriter fw = new FileWriter(archivo);
            PrintWriter pw = new PrintWriter(fw);
            
            for(int i=0; i<Tabla.getRowCount(); i++){
            for(int j=0;j<Tabla.getColumnCount();j++){
                pw.print(Tabla.getValueAt(i,j)+",");
            }
            pw.println();
        }
           pw.close();
           JOptionPane.showMessageDialog(null,"Archivo guardado con exito","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"error al guardar el archivo","Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//fin de guardarArchivo 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        mpdelete = new javax.swing.JMenuItem();
        mpMod = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        tfX = new javax.swing.JTextField();
        tfY = new javax.swing.JTextField();
        tfDato = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        modificarmen = new javax.swing.JMenuItem();
        guardarb = new javax.swing.JMenuItem();
        cargarb = new javax.swing.JMenuItem();
        borrarb = new javax.swing.JMenuItem();

        mpdelete.setText("Eliminar fila");
        mpdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpdeleteActionPerformed(evt);
            }
        });
        popup.add(mpdelete);

        mpMod.setText("Modificar fila");
        mpMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpModActionPerformed(evt);
            }
        });
        popup.add(mpMod);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla.setComponentPopupMenu(popup);
        jScrollPane1.setViewportView(Tabla);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('E');
        jMenu2.setText("Edit");

        modificarmen.setText("modificar");
        modificarmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarmenActionPerformed(evt);
            }
        });
        jMenu2.add(modificarmen);

        guardarb.setText("Guardar");
        guardarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbActionPerformed(evt);
            }
        });
        jMenu2.add(guardarb);

        cargarb.setText("Cargar");
        cargarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarbActionPerformed(evt);
            }
        });
        jMenu2.add(cargarb);

        borrarb.setText("Borrar");
        borrarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbActionPerformed(evt);
            }
        });
        jMenu2.add(borrarb);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfX, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfY, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfDato, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpdeleteActionPerformed
        int filas = Tabla.getSelectedRow();
        if(filas >=0){
            modelo.removeRow(filas);
        } else {
            JOptionPane.showMessageDialog(null, "selecciona una fila para eliminarla ", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    }
    }//GEN-LAST:event_mpdeleteActionPerformed

    private void mpModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpModActionPerformed
        x = Tabla.getSelectedRow();
         y = Tabla.getSelectedColumn();
        tfX.setText(Integer.toString(x));
        tfY.setText(Integer.toString(y));
        tfDato.setText(String.valueOf(Tabla.getValueAt(x, y)));
    }//GEN-LAST:event_mpModActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tabla.setValueAt(tfDato.getText(), x, y);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void modificarmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarmenActionPerformed
        jButton1ActionPerformed(evt);
        
    }//GEN-LAST:event_modificarmenActionPerformed

    private void guardarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbActionPerformed
        guardarArchivo();
    }//GEN-LAST:event_guardarbActionPerformed

    private void cargarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarbActionPerformed
        delTable();
        try {
            cargarArchivos();
        } catch (IOException ex) {
            Logger.getLogger(directorio2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cargarbActionPerformed

    private void borrarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbActionPerformed
        delTable();
    }//GEN-LAST:event_borrarbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(directorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(directorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(directorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(directorio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new directorio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JMenuItem borrarb;
    private javax.swing.JMenuItem cargarb;
    private javax.swing.JMenuItem guardarb;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem modificarmen;
    private javax.swing.JMenuItem mpMod;
    private javax.swing.JMenuItem mpdelete;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JTextField tfDato;
    private javax.swing.JTextField tfX;
    private javax.swing.JTextField tfY;
    // End of variables declaration//GEN-END:variables
}
